FROM node:16

RUN mkdir -p /app
RUN chown -R node:node /app

USER node

WORKDIR /app

COPY --chown=node:node package*.json .

RUN npm install

COPY --chown=node:node . .

EXPOSE 3000

CMD ["npm", "start"]
